// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_API.Data;

#nullable disable

namespace Proyecto_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230321225403_AlimentarTablaVilla")]
    partial class AlimentarTablaVilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_API.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amenity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Fee")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupants")
                        .HasColumnType("int");

                    b.Property<int>("SquareMeter")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrlImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = 0,
                            CreateDate = new DateTime(2023, 3, 21, 17, 54, 2, 877, DateTimeKind.Local).AddTicks(4444),
                            Detail = "Detail of the village...",
                            Fee = 100.0,
                            Name = "Villa Real",
                            Occupants = 2,
                            SquareMeter = 100,
                            UpdateDate = new DateTime(2023, 3, 21, 17, 54, 2, 877, DateTimeKind.Local).AddTicks(4466),
                            UrlImage = ""
                        },
                        new
                        {
                            Id = 2,
                            Amenity = 0,
                            CreateDate = new DateTime(2023, 3, 21, 17, 54, 2, 877, DateTimeKind.Local).AddTicks(4469),
                            Detail = "Detail of the village Juancho...",
                            Fee = 200.0,
                            Name = "Villa Juancho",
                            Occupants = 4,
                            SquareMeter = 200,
                            UpdateDate = new DateTime(2023, 3, 21, 17, 54, 2, 877, DateTimeKind.Local).AddTicks(4470),
                            UrlImage = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
